---
title: "Figure 2"
author: "Stephen Noell"
date: "27 October 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE, 
                      warning=FALSE,
                      fig.align = "left")

```

```{r}
library("here")            # set the path to the folder 
library("GGally")
library("ggplot2")
library("ggpubr")
library("dplyr")
library("tidyverse")
library("svglite") #for saving SVGs

set.seed(57)

```

```{r}
#input .csv files, then transform to umoles instead of nmoles
rawdata_sar_4_short <- read.csv("Uptake_Rdata_htcc7211_4_short.csv", header=TRUE)
model_sar_4_short <- read.csv("Uptake_Rdata_htcc7211_4_short_model.csv", header=TRUE) %>%
  mutate(., Uptake = Uptake/1000)

rawdata_sar_4_long <- read.csv("Uptake_Rdata_htcc7211_4_long.csv", header=TRUE)
model_sar_4_long <- read.csv("Uptake_Rdata_htcc7211_4_long_model.csv", header=TRUE) %>%
  mutate(., Uptake = Uptake/1000)

rawdata_sar_4_preinduced <- read.csv("Uptake_Rdata_htcc7211_4_preinduced.csv", header=TRUE)
model_sar_4_preinduced <- read.csv("Uptake_Rdata_htcc7211_4_preinduced_model.csv",header=TRUE) %>%
  mutate(., Uptake = Uptake/1000)

rawdata_hot_4_short <- read.csv("Uptake_Rdata_hot1a3_4_short.csv", header=TRUE)
model_hot_4_short <- read.csv("Uptake_Rdata_hot1a3_4_short_model.csv", header=TRUE) %>%
  mutate(., Uptake = Uptake/1000)

rawdata_hot_4_long <- read.csv("Uptake_Rdata_hot1a3_4_long.csv", header=TRUE)
model_hot_4_long <- read.csv("Uptake_Rdata_hot1a3_4_long_model.csv", header=TRUE) %>%
  mutate(., Uptake = Uptake/1000)

rawdata_hot_4_preinduced <- read.csv("Uptake_Rdata_hot1a3_4_preinduced.csv", header=TRUE)
model_hot_4_preinduced <- read.csv("Uptake_Rdata_hot1a3_4_preinduced_model.csv",header=TRUE) %>%
  mutate(., Uptake = Uptake/1000)

rawdata_hot_62_long <- read.csv("Uptake_Rdata_hot1a3_62_long.csv", header=TRUE)
model_hot_62_long <- read.csv("Uptake_Rdata_hot1a3_62_long_model.csv", header=TRUE) %>%
  mutate(., Uptake = Uptake/1000)

#input rate files
rates_sar_4_short <- read.csv("Uptake_Rdata_htcc7211_4_short_rates.csv", header=TRUE)

rates_sar_4_long <- read.csv("Uptake_Rdata_htcc7211_4_long_rates.csv", header=TRUE)

rates_sar_4_preinduced <- read.csv("Uptake_Rdata_htcc7211_4_preinduced_rates.csv", header=TRUE)

rates_hot_4_short <- read.csv("Uptake_Rdata_hot1a3_4_short_rates.csv", header=TRUE)

rates_hot_4_long <- read.csv("Uptake_Rdata_hot1a3_4_long_rates.csv", header=TRUE)

rates_hot_4_preinduced <- read.csv("Uptake_Rdata_hot1a3_4_preinduced_rates.csv", header=TRUE)

rates_hot_62_long <- read.csv("Uptake_Rdata_hot1a3_62_long_rates.csv", header=TRUE)

```


```{r}
#set max values

xmax5 <- max(rawdata_sar_4_short$Time, na.rm = TRUE)
xmax6 <- max(rawdata_sar_4_long$Time, na.rm = TRUE)
xmax7 <- max(rawdata_sar_4_preinduced$Time, na.rm = TRUE)
xmax1 <- max(rawdata_hot_4_short$Time, na.rm = TRUE)
xmax2 <- max(rawdata_hot_4_long$Time, na.rm = TRUE)
xmax3 <- max(rawdata_hot_4_preinduced$Time, na.rm = TRUE)
xmax4 <- max(rawdata_hot_62_long$Time, na.rm = TRUE)

```

```{r}
#plots

plot_hot_4_short <- ggplot(rawdata_hot_4_short) +
  geom_point(data = rawdata_hot_4_short, aes(x=Time, y=Uptake, 
                                             color=Type, shape=Type),
             size = 4) +
  geom_line(data = model_hot_4_short, aes(x=Time, y=Uptake,
                                          color=Type),
             size = 0.4) +
  geom_errorbar(data = rawdata_hot_4_short, aes(x=Time, y=Uptake,
                                                ymin=Uptake-StDev, 
                                                ymax=Uptake+StDev,
                                                color=Type), 
                width=(xmax1/20), size = 0.5,
                position=position_dodge(.01)) +
  theme_bw() + 
  scale_colour_manual(values=c("#003f5c","#bc5090", "#ffa600")) +
  labs(x = "Time (min)", y = "LALA taken up (\u00b5mol C/gDW)") +
  theme(axis.title.x = element_text(size=10),          axis.title.y = element_text(size=9),         axis.text = element_text(size=9), legend.position = "none")

plot_hot_4_short_rates <- ggplot(rates_hot_4_short, aes(x = Time, y = Rate, 
                                                        group = Type, fill = Type)) +
  geom_col(stat="identity", position="dodge") +
  theme_bw() +
  scale_fill_manual(values=c("#003f5c","#bc5090", "#ffa600")) +
  labs(x = "Time Range (min)", y = "Rate (\u00b5mol C/gDW/min)") +
  theme(axis.title.x = element_text(size=10),          axis.title.y = element_text(size=9),         axis.text = element_text(size=9), 
        axis.text.x  = element_text(angle = 45,
                                hjust= 1.3, vjust=1.3),
        legend.position = "none") +
  coord_cartesian(ylim = c(0, 20))

```

```{r}

plot_hot_4_long <- ggplot(rawdata_hot_4_long) +
  geom_point(data = rawdata_hot_4_long, aes(x=Time, y=Uptake, 
                                             color=Type, shape=Type),
             size = 4) +
  geom_line(data = model_hot_4_long, aes(x=Time, y=Uptake,
                                          color=Type),
            size = 0.4) +
  geom_errorbar(data = rawdata_hot_4_long, aes(x=Time, y=Uptake,
                                                ymin=Uptake-StDev, 
                                                ymax=Uptake+StDev,
                                                color=Type), 
                width=(xmax2/20), size = 0.5,
                position=position_dodge(.01)) +
  theme_bw() + 
  scale_colour_manual(values=c("#003f5c","#bc5090", "#ffa600")) +
  labs(x = "Time (min)", y = "LALA taken up (\u00b5mol C/gDW)") +
  theme(axis.title.x = element_text(size=10),          axis.title.y = element_text(size=9),         axis.text = element_text(size=9), legend.position = "none")

#order rates properly
hot4long_o <- c("0 - 5", "5 - 8", "8 - 20", "20 - 40")

rates_hot_4_long$Time <- factor(as.character(rates_hot_4_long$Time), levels=hot4long_o)
rates_hot_4_long <- rates_hot_4_long[order(rates_hot_4_long$Time),]

plot_hot_4_long_rates <- ggplot(rates_hot_4_long, aes(x = Time, y = Rate, 
                                                        group = Type, fill = Type)) +
  geom_col(stat="identity", position="dodge") +
  theme_bw() +
  scale_fill_manual(values=c("#003f5c","#bc5090", "#ffa600")) +
  labs(x = "Time Range (min)", y = "Rate (\u00b5mol C/gDW/min)") +
  theme(axis.title.x = element_text(size=10),          axis.title.y = element_text(size=9),         axis.text = element_text(size=9), 
        axis.text.x  = element_text(angle = 45,
                                hjust= 1.3, vjust=1.3),
        legend.position = "none") +
  coord_cartesian(ylim = c(0, 20))

```

```{r}

plot_hot_4_preinduced <- ggplot(rawdata_hot_4_preinduced) +
  geom_point(data = rawdata_hot_4_preinduced, aes(x=Time, y=Uptake, 
                                            color=Type, shape=Type),
             size = 4) +
  geom_line(data = model_hot_4_preinduced, aes(x=Time, y=Uptake,
                                         color=Type),
            size = 0.4) +
  geom_errorbar(data = rawdata_hot_4_preinduced, aes(x=Time, y=Uptake,
                                               ymin=Uptake-StDev, 
                                               ymax=Uptake+StDev,
                                               color=Type), 
                width=(xmax3/20), size = 0.5,
                position=position_dodge(.01)) +
  theme_bw() + 
  scale_colour_manual(values=c("#003f5c","#bc5090", "#ffa600")) +
  labs(x = "Time (min)", y = "LALA taken up (\u00b5mol C/gDW)") +
  theme(axis.title.x = element_text(size=10),          axis.title.y = element_text(size=9),         axis.text = element_text(size=9), legend.position = "none")

plot_hot_4_preinduced_rates <- ggplot(rates_hot_4_preinduced, aes(x = Time, y = Rate, 
                                                        group = Type, fill = Type)) +
  geom_col(stat="identity", position="dodge") +
  theme_bw() +
  scale_fill_manual(values=c("#003f5c","#bc5090", "#ffa600")) +
  labs(x = "Time Range (min)", y = "Rate (\u00b5mol C/gDW/min)") +
  theme(axis.title.x = element_text(size=10),          axis.title.y = element_text(size=9),         axis.text = element_text(size=9), 
        axis.text.x  = element_text(angle = 45,
                                hjust= 1.3, vjust=1.3),
        legend.position = "none") +
  coord_cartesian(ylim = c(0, 20))

```

```{r}

plot_hot_62_long <- ggplot(rawdata_hot_62_long) +
  geom_point(data = rawdata_hot_62_long, aes(x=Time, y=Uptake, 
                                            color=Type, shape=Type),
             size = 4) +
  geom_line(data = model_hot_62_long, aes(x=Time, y=Uptake,
                                         color=Type),
            size = 0.4) +
  geom_errorbar(data = rawdata_hot_62_long, aes(x=Time, y=Uptake,
                                               ymin=Uptake-StDev, 
                                               ymax=Uptake+StDev,
                                               color=Type), 
                width=(xmax4/20), size = 0.5,
                position=position_dodge(.01)) +
  theme_bw() + 
  scale_colour_manual(values=c("#003f5c","#bc5090", "#ffa600")) +
  labs(x = "Time (min)", y = "LALA taken up (\u00b5mol C/gDW)") +
  theme(axis.title.x = element_text(size=10),          axis.title.y = element_text(size=9),         axis.text = element_text(size=9), legend.position = "none")

#order rates properly
hot62long_o <- c("0 - 5", "5 - 10", "10 - 20", "20 - 40")

rates_hot_62_long$Time <- factor(as.character(rates_hot_62_long$Time), levels=hot62long_o)
rates_hot_62_long <- rates_hot_62_long[order(rates_hot_62_long$Time),]

plot_hot_62_long_rates <- ggplot(rates_hot_62_long, aes(x = Time, y = Rate, 
                                                        group = Type, fill = Type)) +
  geom_col(stat="identity", position="dodge") +
  theme_bw() +
  scale_fill_manual(values=c("#003f5c","#bc5090", "#ffa600")) +
  labs(x = "Time Range (min)", y = "Rate (\u00b5mol C/gDW/min)") +
  theme(axis.title.x = element_text(size=10),          axis.title.y = element_text(size=9),         axis.text = element_text(size=9), 
        axis.text.x  = element_text(angle = 45,
                                hjust= 1.3, vjust=1.3),
        legend.position = "none")

```

```{r}
#7211 plots

plot_sar_4_short <- ggplot(rawdata_sar_4_short) +
  geom_point(data = rawdata_sar_4_short, aes(x=Time, y=Uptake, 
                                            color=Type, shape=Type),
             size = 4) +
  geom_line(data = model_sar_4_short, aes(x=Time, y=Uptake,
                                         color=Type),
            size = 0.4) +
  geom_errorbar(data = rawdata_sar_4_short, aes(x=Time, y=Uptake,
                                               ymin=Uptake-StDev, 
                                               ymax=Uptake+StDev,
                                               color=Type), 
                width=(xmax5/20), size = 0.5,
                position=position_dodge(.01)) +
  theme_bw() + 
  scale_colour_manual(values=c("#003f5c","#bc5090", "#ffa600")) +
  labs(x = "Time (min)", y = "LALA taken up (\u00b5mol C/gDW)") +
  theme(axis.title.x = element_text(size=10),          axis.title.y = element_text(size=9),         axis.text = element_text(size=9), legend.position = "none")

plot_sar_4_short_rates <- ggplot(rates_sar_4_short, aes(x = Time, y = Rate, 
                                                        group = Type, fill = Type)) +
  geom_col(stat="identity", position="dodge") +
  theme_bw() +
  scale_fill_manual(values=c("#003f5c","#bc5090", "#ffa600")) +
  labs(x = "Time Range (min)", y = "Rate (\u00b5mol C/gDW/min)") +
  theme(axis.title.x = element_text(size=10),          axis.title.y = element_text(size=9),         axis.text = element_text(size=9), 
        axis.text.x  = element_text(angle = 45,
                                hjust= 1.3, vjust=1.3),
        legend.position = "none") +
  coord_cartesian(ylim = c(0, 0.7))

```

```{r}

plot_sar_4_long <- ggplot(rawdata_sar_4_long) +
  geom_point(data = rawdata_sar_4_long, aes(x=Time, y=Uptake, 
                                             color=Type, shape=Type),
             size = 4) +
  geom_line(data = model_sar_4_long, aes(x=Time, y=Uptake,
                                          color=Type),
            size = 0.4) +
  geom_errorbar(data = rawdata_sar_4_long, aes(x=Time, y=Uptake,
                                                ymin=Uptake-StDev, 
                                                ymax=Uptake+StDev,
                                                color=Type), 
                width=(xmax6/20), size = 0.5,
                position=position_dodge(.01)) +
  theme_bw() + 
  scale_colour_manual(values=c("#003f5c","#bc5090", "#ffa600")) +
  labs(x = "Time (min)", y = "LALA taken up (\u00b5mol C/gDW)") +
  theme(axis.title.x = element_text(size=10),          axis.title.y = element_text(size=9),         axis.text = element_text(size=9), legend.position = "none")

#order rates properly
sar4long_o <- c("0 - 5", "5 - 10", "10 - 20", "20 - 40")

rates_sar_4_long$Time <- factor(as.character(rates_sar_4_long$Time), levels=sar4long_o)
rates_sar_4_long <- rates_sar_4_long[order(rates_sar_4_long$Time),]

plot_sar_4_long_rates <- ggplot(rates_sar_4_long, aes(x = Time, y = Rate, 
                                                        group = Type, fill = Type)) +
  geom_col(stat="identity", position="dodge") +
  theme_bw() +
  scale_fill_manual(values=c("#003f5c","#bc5090", "#ffa600")) +
  labs(x = "Time Range (min)", y = "Rate (\u00b5mol C/gDW/min)") +
  theme(axis.title.x = element_text(size=10),          axis.title.y = element_text(size=9),         axis.text = element_text(size=9), 
        axis.text.x  = element_text(angle = 45,
                                hjust= 1.3, vjust=1.3),
        legend.position = "none") +
  coord_cartesian(ylim = c(0, 0.7))

```

```{r}

plot_sar_4_preinduced <- ggplot(model_sar_4_preinduced) +
  geom_point(data = rawdata_sar_4_preinduced, aes(x=Time, y=Uptake, 
                                             color=Type, shape=Type),
             size = 4) +
  geom_line(data = model_sar_4_preinduced, aes(x=Time, y=Uptake,
                                          color=Type),
            size = 0.4) +
  geom_errorbar(data = rawdata_sar_4_preinduced, aes(x=Time, y=Uptake,
                                                ymin=Uptake-StDev, 
                                                ymax=Uptake+StDev,
                                                color=Type), 
                width=(xmax7/20), size = 0.5,
                position=position_dodge(.01)) +
  theme_bw() + 
  scale_colour_manual(values=c("#003f5c","#bc5090", "#ffa600")) +
  labs(x = "Time (min)", y = "LALA taken up (\u00b5mol C/gDW)") +
  theme(axis.title.x = element_text(size=10), 
        axis.title.y = element_text(size=9),
        axis.text = element_text(size=9),
        legend.position = "none")

plot_sar_4_preinduced_rates <- ggplot(rates_sar_4_preinduced, aes(x = Time, y = Rate, 
                                                        group = Type, fill = Type)) +
  geom_col(stat="identity", position="dodge") +
  theme_bw() +
  scale_fill_manual(values=c("#003f5c","#bc5090", "#ffa600")) +
  labs(x = "Time Range (min)", y = "Rate (\u00b5mol C/gDW/min)") +
  theme(axis.title.x = element_text(size=10),          axis.title.y = element_text(size=9),         axis.text = element_text(size=9), 
        axis.text.x  = element_text(angle = 45,
                                hjust= 1.3, vjust=1.3),
        legend.position = "none") +
  coord_cartesian(ylim = c(0, 0.7))

```

```{r}
#final plot

fig1 <- ggarrange(plot_sar_4_long, plot_sar_4_long_rates,
                  plot_hot_4_long, plot_hot_4_long_rates,
                  plot_sar_4_short, plot_sar_4_short_rates,
                  plot_hot_4_short, plot_hot_4_short_rates,
                  plot_sar_4_preinduced, plot_sar_4_preinduced_rates,
                  plot_hot_4_preinduced, plot_hot_4_preinduced_rates,
                  plot_hot_62_long, plot_hot_62_long_rates,
          labels = c("A", "B", "C", "D", "E", "F", "G",
                     "H", "I", "J", "K", "L", "M", "N"),
          ncol = 4, nrow = 4,
          label.y = 0.2)

#ggsave("Figure 1.png", fig1, width = 240, height = 240, units = "mm", dpi = 300)

#ggsave("Figure 1.svg", fig1, width = 240, height = 240, units = "mm", dpi = 300)
```

```{r}
#make insets for Fig1I and K
#7211
inset_sar_preinduced <- ggplot(rawdata_sar_4_preinduced) +
  geom_point(data = rawdata_sar_4_preinduced, aes(x=Time, y=Uptake, 
                                            color=Type, shape=Type),
             size = 1.5) +
  geom_line(data = model_sar_4_preinduced, aes(x=Time, y=Uptake,
                                         color=Type),
            size = 0.2) +
  geom_errorbar(data = rawdata_sar_4_preinduced, aes(x=Time, y=Uptake,
                                               ymin=Uptake-StDev, 
                                               ymax=Uptake+StDev,
                                               color=Type), 
                width=(0.01), size = 0.2) +
  theme_bw() + 
  scale_colour_manual(values=c("#003f5c","#bc5090", "#ffa600")) +
  theme(axis.text = element_text(size=6),
        axis.title = element_blank(),
        legend.position = "none",
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank()) +
  coord_cartesian(xlim = c(0,1), ylim = c(0,0.7))

inset_sar_preinduced

#ggsave("Figure 1I inset.png", inset_sar_preinduced, width = 28, height = 24, units = "mm", dpi = 300)

#HOT
inset_hot_preinduced <- ggplot(rawdata_hot_4_preinduced) +
  geom_point(data = rawdata_hot_4_preinduced, aes(x=Time, y=Uptake, 
                                            color=Type, shape=Type),
             size = 1.5) +
  geom_line(data = model_hot_4_preinduced, aes(x=Time, y=Uptake,
                                         color=Type),
            size = 0.2) +
  geom_errorbar(data = rawdata_hot_4_preinduced, aes(x=Time, y=Uptake,
                                               ymin=Uptake-StDev, 
                                               ymax=Uptake+StDev,
                                               color=Type), 
                width=(0.01), size = 0.2) +
  theme_bw() + 
  scale_colour_manual(values=c("#003f5c","#bc5090", "#ffa600")) +
  theme(axis.text = element_text(size=6),
        axis.title = element_blank(),
        legend.position = "none",
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank()) +
  coord_cartesian(xlim = c(0,1), ylim = c(0,8))

inset_hot_preinduced

#ggsave("Figure 1K inset.png", inset_hot_preinduced, width = 28, height = 26, units = "mm", dpi = 300)


```
