---
title: "Functional differences olig/copio"
author: "Stephen Noell"
date: "23/05/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE, 
                      warning = FALSE,
                      fig.align = "center",
                      fig.width = 10,
                      fig.height = 6)
```


```{r}

# Libraries
library("tidyverse")       # data wrangling and visualisation
library("here")            # set the path to the folder
library("ggplot2")
library("ggpubr") #for putting figs together
library("RColorBrewer") #for color palettes
library("svglite") #for saving SVGs
library("reshape2")
library("formattable")
library("stringr")


set.seed(57)
```

```{r}
#data loading
metadata <- read_csv("metadata_all2.csv", show_col_types = FALSE) %>%
  as.data.frame(.)

all_cogs <- list.files(pattern="*.cog") %>%
  map_df(~read_tsv(., col_types = cols(.default = "c")))

map <- read_tsv("assemid_to_filename.tab") %>%
  as.data.frame(.) %>%
  dplyr::rename(species = 2)

COG_categories <- read_csv("COG_categories.csv", col_types = cols(.default = "c")) %>%
  as.data.frame(.)

EGGO <- read.csv("EGGO.csv")

NA_categories <- read.csv("NA_categories.csv")

#categorize each genome as oligotroph or copiotroph according to Weissman's definition
EGGO$accession <- EGGO$Assembly %>% substr(1,15)
EGGO$lifestyle <- ""
EGGO["lifestyle"][which(EGGO$d<5), ] <- "Copiotroph"
EGGO["lifestyle"][which(EGGO$d>=5), ] <- "Oligotroph"
EGGO_f <- EGGO %>%
  select(accession, lifestyle)

```


```{r}
#clean up data
all_cogs_df <- as.data.frame(all_cogs) %>%
  select(1, 2, 4, 5, 6) %>%
  dplyr::rename(species = 1)

#change assembly to correct identifier
all_cogs_df_1 <- all_cogs_df %>%
  left_join(., map, by = "species") %>%
  select(1, 3, 4, 5, 6)

###change NA values to correct COG categories
all_cogs_df_2 <- all_cogs_df_1 %>%
  full_join(., NA_categories, by = "COG") %>%
  mutate(category = coalesce(category.y, category.x),
         name = coalesce(name.x, name.y)) %>%
  dplyr::select(accession, species, COG, category, name)
  
#separate proteins that have multiple COG categories into their own separate row
all_cogs_df_3 <- all_cogs_df_2 %>%
  separate_rows(., category, sep = "") %>%
  na_if("") %>%
  na.omit %>%
  as.data.frame(.)

```

```{r}
#split COG category K into transcriptional regulation vs. non
all_cogs_df_split1 <- all_cogs_df_3 %>%
    mutate(COG2 = case_when(
      str_detect(name, "ranscriptional regulator") ~ "K: transcriptional regulators",
      category == "K" & !str_detect(name, "ranscriptional regulator") ~ "K: other",
      TRUE ~ category)) %>%
  select(accession, name, COG2) %>%
  dplyr::rename(category = COG2)

#split COG category T into chemotaxis vs. non
all_cogs_df_split2 <- all_cogs_df_split1 %>%
    mutate(COG2 = case_when(
      str_detect(name, "hemotaxis") ~ "T: Chemotaxis",
      category == "T" & !str_detect(name, "hemotaxis") ~ "T: other",
      TRUE ~ category)) %>%
  select(accession, name, COG2) %>%
  dplyr::rename(category = COG2)

#split COG category N into flagella vs. non
all_cogs_df_split3 <- all_cogs_df_split2 %>%
    mutate(COG2 = case_when(
      str_detect(name, "lagell") ~ "N: flagella",
      category == "N" & !str_detect(name, "lagell") ~ "N: other",
      TRUE ~ category)) %>%
  select(accession, name, COG2) %>%
  dplyr::rename(category = COG2)

all_cogs_df_split <- all_cogs_df_split3

#for each assembly id, calculate proportion of unique COG categories
cogs_prop <- all_cogs_df_split %>%
  dplyr::group_by(accession, category) %>%
  dplyr::summarize(count=n()) %>%
  mutate(., prop = count / sum(count)) %>%
  ungroup(.) %>%
  as.data.frame(.)

```


```{r}
#test for significant enrichment
copiotrophs <- EGGO %>%
  filter(., d<5) %>%
  select(accession) %>%
  inner_join(., cogs_prop, by = "accession") %>%
  select(., category, prop) %>%
  dplyr::rename(COG = category)

copiotrophs$Copiotroph <- "TRUE"

oligotrophs <- EGGO %>%
  filter(., d>=5) %>%
  select(accession) %>%
  inner_join(., cogs_prop, by = "accession") %>%
  select(., category, prop) %>%
  dplyr::rename(COG = category)

oligotrophs$Copiotroph <- "FALSE"

prop_mix_df <- rbind(copiotrophs, oligotrophs)

test_df <- data.frame(COG=character(),
                      pval=numeric(),
                      Diff=numeric())

for(COG_i in unique(prop_mix_df$COG)){
  df <- prop_mix_df %>% subset(COG==COG_i)
  test_df <- rbind(test_df,
                   data.frame(COG=COG_i,
                              pval=wilcox.test(df$prop[df$Copiotroph == "TRUE"], 
                                               df$prop[df$Copiotroph == "FALSE"])$p.value,
                              Diff=mean(df$prop[df$Copiotroph == "TRUE"])-mean(df$prop[df$Copiotroph == "FALSE"])))
}
test_df$p.adj <- p.adjust(test_df$pval)

test_df$Significant <- ""
test_df["Significant"][which(test_df$p.adj < 0.05), ] <- "Yes"
test_df["Significant"][which(test_df$p.adj > 0.05), ] <- "No"

test_df <- test_df %>%
 mutate(Number = 1:n())

test_df <- test_df %>%
  inner_join(., COG_categories, by = "COG")
```

```{r}
#For this paper, restrict to just categories of interest
test_df_v2 <- test_df %>%
  filter(COG_category == "K: Transcription - Other" | 
           COG_category == "K: Transcription - Transcriptional Regulators" |
           COG_category == "N: Cell motility - Flagella" | 
           COG_category == "N: Cell motility - Other" |
           COG_category == "T: Signal Transduction - Chemotaxis" |
           COG_category == "T:  Signal Transduction - Other")


enrich_plot <- ggplot(test_df_v2, aes(x = COG_category, y = Diff, fill = Significant)) +
  geom_col(color = "#1f78b4") +
  theme_bw() +
  theme(axis.text.x = element_text(size=12),
        axis.title.x = element_text(size = 12),
        axis.text.y = element_text(size = 12),
        axis.title.y = element_text(size = 12),
        legend.position = "bottom") +
  coord_flip(ylim = c(-0.015, 0.015))+
  xlab("COG Category") +
  ylab("Difference in mean enrichment \n (Copiotroph - Oligotroph)") +
  scale_fill_manual(values=c("white","#1f78b4"))

enrich_plot

#write.csv(test_df_v2, "Transcriptional regulation.csv", row.names = FALSE)

```

```{r}
list_genomes <- as.data.frame(unique(all_cogs_df_split$accession)) %>%
  dplyr::rename(., "accession" = 1)

#Is there actually a difference in #flagella genes between copiotrophs and oligotrophs?

#take list of COGS that's already been split

#for each assembly id, calculate number of flagellar genes
cogs_prop <- all_cogs_df_split %>%
  dplyr::group_by(accession, category) %>%
  dplyr::summarize(count=n()) %>%
  ungroup(.) %>%
  as.data.frame(.)

#normalize flagella proportion to genome completeness
flag <- cogs_prop %>%
  filter(., category == "N: flagella") %>%
  inner_join(., metadata, by = "accession") %>%
  mutate(flag.norm = count / completeness) %>%
  select(accession, flag.norm)

flag_merged <- flag %>%
  full_join(., list_genomes)

flag_merged[is.na(flag_merged)] <- 0

flag_lifestyle <- EGGO_f %>%
  inner_join(., flag_merged, by = "accession")

flag_oli_mean <- flag_lifestyle %>%
  filter(., lifestyle == "Oligotroph")
median(flag_oli_mean$flag.norm)

flag_copi_mean <- flag_lifestyle %>%
  filter(., lifestyle == "Copiotroph")
median(flag_copi_mean$flag.norm)

flag_plot <- ggplot(flag_lifestyle, aes(x = lifestyle, y = flag.norm,
                                         color = lifestyle)) +
  geom_boxplot() +
  geom_jitter(size = 0.7) +
  theme_bw() +
  theme(
    axis.text.x = element_blank(),
    axis.title.x = element_blank(),
    axis.ticks.x = element_blank()
  ) +
  scale_color_manual(values=c("#4dac26","#d01c8b")) +
  xlab("Lifestyle") +
  ylab("Flagellar genes\nin each genome")

flag_plot

p.adjust(wilcox.test(flag_lifestyle$flag.norm[flag_lifestyle$lifestyle == "Copiotroph"], 
            flag_lifestyle$flag.norm[flag_lifestyle$lifestyle == "Oligotroph"])$p.value)
```


```{r}
#compare count of necessary flagellar genes between copios and oligos
############### flhA gene

flha_old <- all_cogs_df_split %>%
  filter(name == "Flagellar biosynthesis protein FlhA")%>%
  dplyr::group_by(accession, category) %>%
  dplyr::summarize(count=n()) %>%
  ungroup(.) %>%
  as.data.frame(.)

flha <- flha_old %>%
  inner_join(., metadata, by = "accession") %>%
  mutate(flha.norm = count / completeness) %>%
  select(accession, flha.norm)

flha_merged <- flha %>%
  full_join(., list_genomes)

flha_merged[is.na(flha_merged)] <- 0

flha_lifestyle <- EGGO_f %>%
  inner_join(., flha_merged, by = "accession")

flha_oli_mean <- flha_lifestyle %>%
  filter(., lifestyle == "Oligotroph")
mean(flha_oli_mean$flha.norm)

flha_copi_mean <- flha_lifestyle %>%
  filter(., lifestyle == "Copiotroph")
mean(flha_copi_mean$flha.norm)

flha_plot <- ggplot(flha_lifestyle, aes(x = flha.norm,
                                         fill = lifestyle)) +
  geom_density(alpha=.3) +
  theme_bw() +
  theme (legend.position = "none") +
  scale_fill_manual(values=c("#4dac26","#d01c8b")) +
  xlab("Count of flhA genes in each genome") +
  ylab("Density")

flha_plot

p.adjust(wilcox.test(flha_lifestyle$flha.norm[flha_lifestyle$lifestyle == "Copiotroph"], 
            flha_lifestyle$flha.norm[flha_lifestyle$lifestyle == "Oligotroph"])$p.value)

```

```{r}
################# flgA gene
flga_old <- all_cogs_df_split %>%
  filter(name == "Flagellar basal body P-ring formation protein FlgA")%>%
  dplyr::group_by(accession, category) %>%
  dplyr::summarize(count=n()) %>%
  ungroup(.) %>%
  as.data.frame(.)

flga <- flga_old %>%
  inner_join(., metadata, by = "accession") %>%
  mutate(flga.norm = count / completeness) %>%
  select(accession, flga.norm)

flga_merged <- flga %>%
  full_join(., list_genomes)

flga_merged[is.na(flga_merged)] <- 0

flga_lifestyle <- EGGO_f %>%
  inner_join(., flga_merged, by = "accession")

flga_oli_mean <- flga_lifestyle %>%
  filter(., lifestyle == "Oligotroph")
mean(flga_oli_mean$flga.norm)

flga_copi_mean <- flga_lifestyle %>%
  filter(., lifestyle == "Copiotroph")
mean(flga_copi_mean$flga.norm)

flga_plot <- ggplot(flga_lifestyle, aes(x = flga.norm,
                                         fill = lifestyle)) +
  geom_density(alpha=.3) +
  theme_bw() +
  theme (legend.position = "none") +
  scale_fill_manual(values=c("#4dac26","#d01c8b")) +
  xlab("Count of flgA genes in each genome") +
  ylab("Density")

flga_plot

p.adjust(wilcox.test(flga_lifestyle$flga.norm[flga_lifestyle$lifestyle == "Copiotroph"], 
            flga_lifestyle$flga.norm[flga_lifestyle$lifestyle == "Oligotroph"])$p.value)

```

```{r}
###Look at metadata for this sample set

metadata_all <- EGGO_f %>%
  inner_join(., metadata, by = "accession") %>%
  mutate(., size = Size / 1000000) %>%
  dplyr::rename(., gc_content = 15)

#Genome size - oligotrophs predicted to have smaller genomes
lifestyle_genome_size <- ggplot(metadata_all, aes(x = lifestyle, y = size,
                                                  color = lifestyle)) +
  geom_boxplot() +
  geom_jitter(size = 0.7) +
  theme_bw() +
  theme(
    axis.text.x = element_blank(),
    axis.title.x = element_blank(),
    axis.ticks.x = element_blank()
  ) +
  scale_color_manual(values=c("#4dac26","#d01c8b")) +
  xlab("Lifestyle") +
  ylab("Genome size\n(mbp)")

lifestyle_genome_size

size_copio <- metadata_all %>%
  filter(., lifestyle == "Copiotroph")
size_copio <- mean(size_copio$size)

size_oligo <- metadata_all %>%
  filter(., lifestyle == "Oligotroph")
size_oligo <- mean(size_oligo$size)

size_copio
size_oligo

#GC content - oligotrophs predicted to have lower GC
lifestyle_gc <- ggplot(metadata_all, aes(x = lifestyle, y = gc_content,
                                         color = lifestyle)) +
  geom_boxplot() +
  geom_jitter(size = 0.7) +
  theme_bw() +
  theme(
    axis.text.x = element_blank(),
    axis.title.x = element_blank(),
    axis.ticks.x = element_blank()
  ) +
  scale_color_manual(values=c("#4dac26","#d01c8b")) +
  xlab("Lifestyle") +
  ylab("GC Content (%)")

lifestyle_gc

gc_copio <- metadata_all %>%
  filter(., lifestyle == "Copiotroph")
gc_copio <- mean(gc_copio$gc_content)

gc_oligo <- metadata_all %>%
  filter(., lifestyle == "Oligotroph")
gc_oligo <- mean(gc_oligo$gc_content)

gc_copio
gc_oligo

gc_genome <- ggarrange(lifestyle_genome_size, lifestyle_gc, flag_plot,
                       labels = c("A", "B", "C"),
                       nrow = 1,
                       ncol = 3,
                       common.legend = TRUE)
gc_genome

```

```{r}

freq_dist <- ggarrange(flha_plot, flga_plot,
                       labels = c("D", "E"),
                       nrow = 1,
                       ncol = 2)

freq_dist
```

```{r}
#Final plot

final_plot <- ggarrange(gc_genome, freq_dist, enrich_plot,
                       labels = c("", "", "F"),
                       nrow = 3,
                       ncol = 1,
                       heights = c(0.7, 0.7, 1))
final_plot

#ggsave("Figure 1_functional_diff.png", final_plot, width = 200, height = 180, units = "mm",dpi = 300)
#ggsave("Figure 1_functional_diff.svg", final_plot, width = 200, height = 180, units = "mm",dpi = 300)

```
